name: Feature Request
description: Request something to be added to P-Slice
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: What feature do you want to get added on the **P-Slice** engine?
    validations:
      required: true
